language: c++
compiler:
  - gcc
  - clang
env:
  global:
    - GCC_VERSION="4.9" 
    - BII_BOOST_VERBOSE="ON"
  matrix:
    - BII_BOOST_GLOBAL_USE_STATIC_LIBS="ON"
    - BII_BOOST_GLOBAL_USE_STATIC_LIBS="OFF"
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq

  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-${GCC_VERSION}; fi
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq gcc-${GCC_VERSION}; fi
  - if [ "$CXX" == "g++" ]; then sudo ln -s -f $(which g++-${GCC_VERSION}) /usr/bin/g++ ; fi
  - if [ "$CXX" == "g++" ]; then sudo ln -s -f $(which gcc-${GCC_VERSION}) /usr/bin/gcc ; fi

  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - if [ "$CXX" == "clang++" ]; then cwd=$(pwd); fi
  - if [ "$CXX" == "clang++" ]; then export CXXFLAGS="-std=c++0x -stdlib=libc++"; fi
  - if [ "$CXX" == "clang++" ]; then svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk libcxx; fi
  - if [ "$CXX" == "clang++" ]; then cd libcxx/lib && bash buildit; fi
  - if [ "$CXX" == "clang++" ]; then sudo cp ./libc++.so.1.0 /usr/lib/; fi
  - if [ "$CXX" == "clang++" ]; then sudo mkdir /usr/include/c++/v1; fi
  - if [ "$CXX" == "clang++" ]; then cd .. && sudo cp -r include/* /usr/include/c++/v1/; fi
  - if [ "$CXX" == "clang++" ]; then cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so; fi
  - if [ "$CXX" == "clang++" ]; then sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd; fi
install:
  - wget http://apt.biicode.com/install.sh && chmod +x install.sh && ./install.sh
  - bii setup:cpp
  - $CXX --version 
  - configure_params="-DCMAKE_CXX_COMPILER=$(which $CXX) -DBII_BOOST_VERBOSE=${BII_BOOST_VERBOSE} -DBII_BOOST_GLOBAL_USE_STATIC_LIBS=${BII_BOOST_GLOBAL_USE_STATIC_LIBS}" 
script:
  - bii init #Remember: bii/ folder ignored on git repo
  - bii find --update
  - bii cpp:configure $configure_params || bii cpp:configure $configure_params
  - bii cpp:build
