language: c++
compiler: gcc
env:
  global:
    - GCC_VERSION="4.9" 
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq

  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-${GCC_VERSION}; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq gcc-${GCC_VERSION}; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
install:
  - wget http://apt.biicode.com/install.sh && chmod +x install.sh && ./install.sh
  - bii setup:cpp
script:
  - bii init #Remember: bii/ folder ignored on git repo
  - bii find --update
  - bii cpp:configure -DCMAKE_CXX_COMPILER=$(which $CXX)
  - bii cpp:build
